//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABDC.DALOldNUBE
{
    using System;
    using System.Collections.Generic;
    
    public partial class JournalMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public JournalMaster()
        {
            this.JournalDetails = new HashSet<JournalDetail>();
        }
    
        public decimal JournalId { get; set; }
        public Nullable<decimal> EntryNo { get; set; }
        public Nullable<System.DateTime> JournalDate { get; set; }
        public string HQNo { get; set; }
        public string Fund { get; set; }
        public string VoucherNo { get; set; }
        public string Status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JournalDetail> JournalDetails { get; set; }
    }
}
