//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABDC.DALOld
{
    using System;
    using System.Collections.Generic;
    
    public partial class JournalDetail
    {
        public decimal JDId { get; set; }
        public Nullable<decimal> JournalID { get; set; }
        public Nullable<decimal> LedgerID { get; set; }
        public Nullable<double> DrAmt { get; set; }
        public Nullable<double> CrAmt { get; set; }
        public string Narration { get; set; }
    
        public virtual JournalMaster JournalMaster { get; set; }
        public virtual Ledger Ledger { get; set; }
    }
}
