//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABDC.DALOld
{
    using System;
    using System.Collections.Generic;
    
    public partial class LedgerOP
    {
        public decimal LedgerOPID { get; set; }
        public decimal LedgerID { get; set; }
        public string Fund { get; set; }
        public Nullable<double> DrAmt { get; set; }
        public Nullable<double> CrAmt { get; set; }
    
        public virtual Ledger Ledger { get; set; }
    }
}
