//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABDC.DALOld
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Nube_Old01Entities : DbContext
    {
        public Nube_Old01Entities()
            : base("name=Nube_Old01Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AccountGroup> AccountGroups { get; set; }
        public virtual DbSet<Ledger> Ledgers { get; set; }
        public virtual DbSet<ViewLedger> ViewLedgers { get; set; }
        public virtual DbSet<ViewLedgerGroup> ViewLedgerGroups { get; set; }
        public virtual DbSet<ViewLedgerJournal> ViewLedgerJournals { get; set; }
        public virtual DbSet<ViewLedgerOpening> ViewLedgerOpenings { get; set; }
        public virtual DbSet<ViewLedgerPayment> ViewLedgerPayments { get; set; }
        public virtual DbSet<ViewLedgerReceipt> ViewLedgerReceipts { get; set; }
        public virtual DbSet<ViewLedgerReport> ViewLedgerReports { get; set; }
        public virtual DbSet<ViewTrialBalance> ViewTrialBalances { get; set; }
        public virtual DbSet<JournalDetail> JournalDetails { get; set; }
        public virtual DbSet<JournalMaster> JournalMasters { get; set; }
        public virtual DbSet<LedgerOP> LedgerOPs { get; set; }
        public virtual DbSet<PaymentDetail> PaymentDetails { get; set; }
        public virtual DbSet<PaymentMaster> PaymentMasters { get; set; }
        public virtual DbSet<ReceiptDetail> ReceiptDetails { get; set; }
        public virtual DbSet<ReceiptMaster> ReceiptMasters { get; set; }
    }
}
