//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABDC.DALOld
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PaymentMaster()
        {
            this.PaymentDetails = new HashSet<PaymentDetail>();
            this.PaymentDetails1 = new HashSet<PaymentDetail>();
        }
    
        public decimal PaymentId { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
        public decimal LedgerId { get; set; }
        public string PaymentMode { get; set; }
        public Nullable<double> PayAmount { get; set; }
        public string RefNo { get; set; }
        public string Status { get; set; }
        public Nullable<double> ExtraCharge { get; set; }
        public string ChequeNo { get; set; }
        public Nullable<System.DateTime> chequeDate { get; set; }
        public string Narration { get; set; }
        public Nullable<decimal> EntryNo { get; set; }
        public string Fund { get; set; }
        public Nullable<System.DateTime> ClearDate { get; set; }
        public string PayTo { get; set; }
        public string VoucherNo { get; set; }
    
        public virtual Ledger Ledger { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PaymentDetail> PaymentDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PaymentDetail> PaymentDetails1 { get; set; }
    }
}
