//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABDC.DALOldNUBE
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentDetail
    {
        public decimal PDID { get; set; }
        public Nullable<decimal> PaymentId { get; set; }
        public Nullable<decimal> LedgerId { get; set; }
        public string Narration { get; set; }
        public Nullable<double> Amount { get; set; }
    
        public virtual Ledger Ledger { get; set; }
        public virtual Ledger Ledger1 { get; set; }
        public virtual Ledger Ledger2 { get; set; }
        public virtual Ledger Ledger3 { get; set; }
        public virtual PaymentMaster PaymentMaster { get; set; }
        public virtual PaymentMaster PaymentMaster1 { get; set; }
    }
}
