//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABDB.DALOldFMCG
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseDetail
    {
        public decimal PDId { get; set; }
        public string PDCode { get; set; }
        public string PurchaseCode { get; set; }
        public string POCode { get; set; }
        public string ProductCode { get; set; }
        public Nullable<double> Rate { get; set; }
        public Nullable<double> Quantity { get; set; }
        public string UOM { get; set; }
        public string TaxPer { get; set; }
        public Nullable<double> DisPer { get; set; }
    }
}
