//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABDB.DALOldFMCG
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public decimal CustomerId { get; set; }
        public string CustomerCode { get; set; }
        public string LedgerName { get; set; }
        public string CustomerName { get; set; }
        public string AddressLine { get; set; }
        public string TelePhoneNo { get; set; }
        public string MobileNo { get; set; }
        public string EMailId { get; set; }
        public string CST { get; set; }
        public string TinNo { get; set; }
        public Nullable<decimal> CreditDays { get; set; }
        public Nullable<double> CreditLimits { get; set; }
    }
}
