//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABDB.DALOldFMCG
{
    using System;
    using System.Collections.Generic;
    
    public partial class UnitsOfMeasurement
    {
        public decimal UOMId { get; set; }
        public string UOMCode { get; set; }
        public string UOMSymbol { get; set; }
        public string formalname { get; set; }
    }
}
